apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: hubitat-integrations-local
  name: hubitat-integrations-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hubitat-integrations-local
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hubitat-integrations-local
    spec:
      containers:
      - image: public.ecr.aws/w9b0n8x2/hubitat-integrations-local:raspberrypi
        name: hubitat-integrations-local
        securityContext:
          # Needed to access the hosts bluetooth stack
          privileged: true